// THIS FILE IS GENERATED BY PYRIN ZOD CODE GENERATOR
import { z } from "zod";

export const Serie = z.object({
  id: z.string(),
  name: z.string(),
  cover: z.string(),
  chapterCount: z.number(),
});
export type Serie = z.infer<typeof Serie>;

export const ChapterUserData = z.object({
  isMarked: z.boolean(),
});
export type ChapterUserData = z.infer<typeof ChapterUserData>;

export const Chapter = z.object({
  serieId: z.string(),
  number: z.number(),
  title: z.string(),
  coverArt: z.string(),
  user: ChapterUserData.nullable().optional(),
});
export type Chapter = z.infer<typeof Chapter>;

export const Bookmark = z.object({
  chapterNumber: z.number(),
  page: z.number(),
});
export type Bookmark = z.infer<typeof Bookmark>;

export const SerieUserData = z.object({
  bookmark: Bookmark.nullable().optional(),
});
export type SerieUserData = z.infer<typeof SerieUserData>;

export const GetSeries = z.object({
  series: z.array(Serie),
});
export type GetSeries = z.infer<typeof GetSeries>;

export const GetSerieById = z.object({
  id: z.string(),
  name: z.string(),
  cover: z.string(),
  chapterCount: z.number(),
  user: SerieUserData.nullable(),
});
export type GetSerieById = z.infer<typeof GetSerieById>;

export const GetSerieChaptersById = z.object({
  chapters: z.array(Chapter),
});
export type GetSerieChaptersById = z.infer<typeof GetSerieChaptersById>;

export const GetChapters = z.object({
  chapters: z.array(Chapter),
});
export type GetChapters = z.infer<typeof GetChapters>;

export const GetChapterById = z.object({
  serieId: z.string(),
  number: z.number(),
  title: z.string(),
  coverArt: z.string(),
  user: ChapterUserData.nullable().optional(),
  nextChapter: z.number().nullable(),
  prevChapter: z.number().nullable(),
  pages: z.array(z.string()),
});
export type GetChapterById = z.infer<typeof GetChapterById>;

export const GetLibraryStatus = z.object({
  syncing: z.boolean(),
});
export type GetLibraryStatus = z.infer<typeof GetLibraryStatus>;

