// THIS FILE IS GENERATED BY PYRIN JSGEN CODE GENERATOR
import { z } from "zod";

export const Serie = z.object({
  id: z.string(),
  name: z.string(),
  cover: z.string(),
  chapterCount: z.number(),
});
export type Serie = z.infer<typeof Serie>;

export const Chapter = z.object({
  serieId: z.string(),
  number: z.number(),
  title: z.string(),
});
export type Chapter = z.infer<typeof Chapter>;

export const ChapterUserData = z.object({
  isMarked: z.boolean(),
});
export type ChapterUserData = z.infer<typeof ChapterUserData>;

export const GetSeries = z.object({
  series: z.array(Serie),
});
export type GetSeries = z.infer<typeof GetSeries>;

export const GetSerieById = Serie;
export type GetSerieById = z.infer<typeof GetSerieById>;

export const GetSerieChaptersById = z.object({
  chapters: z.array(Chapter),
});
export type GetSerieChaptersById = z.infer<typeof GetSerieChaptersById>;

export const GetChapters = z.object({
  chapters: z.array(Chapter),
});
export type GetChapters = z.infer<typeof GetChapters>;

export const GetChapterById = z.object({
  serieId: z.string(),
  number: z.number(),
  title: z.string(),
  nextChapter: z.number().optional().nullable(),
  prevChapter: z.number().optional().nullable(),
  pages: z.array(z.string()),
  user: ChapterUserData.optional().nullable(),
});
export type GetChapterById = z.infer<typeof GetChapterById>;

